### PR TITLE
Fix StickerGif

### PR DESCRIPTION
**Pull request by lxndr-rl**
-Update wa-automate to 3.2.6

-Add start script

-Update chromiumArgs (no puppeteer args)

-Add ForceRefocus (to prevent bot stops when open whatsapp web)

-Reply when doesnt send an image (sticker command)

### CODE REVIEW

**Comment by lxndr-rl** [comment]
Already test it 
image

**Review by mzrtamp — APPROVED** [review]

**Comment by lxndr-rl** [comment]
Please change headless false to true. I forget it 😓

**Comment by mzrtamp** [comment]
Bruh

**Comment by mzrtamp** [comment]
Working on it

**Pull request merged**
