### PR TITLE
refactor(StickerCommand): code refactoring due to @open-wa/wa-automate changes

### PR DESCRIPTION
**Pull request by lxndr-rl**
Bot fixed and tested on latest library version `"@open-wa/wa-automate": "^3.10.15"` and `"@open-wa/wa-decrypt": "^3.1.0"`

Sticker fixed (static and gif/video) with metadata
image

waBOT

### CODE REVIEW

**Comment by lxndr-rl** [comment]
#61 and #50 sorry for the delay

**Review by mzrtamp — APPROVED** [review]
Big Thanks!

**Review by Waxaranai — CHANGES_REQUESTED** [review]
Use object deconstructor when importing `prefix`

**Comment by lxndr-rl** [comment]
> Use object deconstructor when importing `prefix`
```javascript
const { prefix } = require("./config.json");
```
this?

**Comment by Waxaranai** [comment]
LGTM!

**Comment by mzrtamp** [comment]
> this?
@lxndr-rl don't worry, I did that for you

**Review by mzrtamp — APPROVED** [review]
Great work

**Pull request merged**
