### PR TITLE
add gif to sticker

### PR DESCRIPTION
**Pull request by lxndr-rl**

### CODE REVIEW

**Comment by lxndr-rl** [comment]
I forget add dependencies to package.json sorry

```json
"child_process": "^1.0.2",
"fs-extra": "^9.1.0"
```
Don't forget install `gify` command

**Review by mzrtamp — COMMENTED** [review]
Have you tested it?

**Review by mzrtamp — APPROVED** [review]
Nvm, I will try to solve this by myself, thanks for your contribution!

**Comment by lxndr-rl** [comment]
yes, i use it on my bot. 
here some commands i did

image

**Comment by mzrtamp** [comment]
> yes, i use it on my bot.
> here some commands i did
> 
> image

Uhh try to test them for this project, I don't have a mobile to do it

**Comment by lxndr-rl** [comment]
I use this project as base. (With some changes like Owner commands, disable commands, alternative commands)

**Comment by mzrtamp** [comment]
> I use this project as base. (With some changes like Owner commands, disable commands, alternative commands)

Yea I know that but I need your help to re-test this project by `git clone` again and start over 0, can I?

**Comment by mzrtamp** [comment]
Because sometimes there's an error :/

**Comment by lxndr-rl** [comment]
Yea I can. Wait please

**Comment by kevinviana** [comment]
hi, i tested it, dosen't works... the command 
`exec(`gify ./assets/stickers/sticker.mp4 ./assets/stickers/output.gif --fps=60 --scale=240:-1`, async (error, stdout, stderr)`
doesn't works!
screenShot

**Pull request merged**
